### PR TITLE
Fix trade duration issue

### PR DESCRIPTION
**Pull request by DanSallau**
Hi ,

Attached should fix a possible issue in our duration that may arises as noticed here https://trello.com/c/44VJcERz/165-nok-forex-breaks-trade .

### CODE REVIEW

**Comment by borisyankov** [comment]
To me this code starts looking messier and messier.
We shouldn't rush bug fixes at the cost of clarity and good code.
Not sure how correct or optimal the approach is in this case... 
@qingweibinary - ok to merge or comments?

**Comment by nuruddeensalihu** [comment]
This should come along with the fix yesterday . Didn't notice until Qinwei pointed out. It would break without this actually.

**Comment by qingweibinary** [comment]
I think this is related to the pr I commented on #229

this PR solve it using some duplication, which I think is acceptable since we already abstract them.
To further abstract we might get some funny function like

`getDefaultBarrierAndDuration`

the code is very clean but I think less to do with this PR, more to the original structure.

**Comment by qingweibinary** [comment]
One way to make it more concise (but maybe a bit arbritary)

is to give onTypeChange a parameter to decide whether to use old value or not

@nuruddeensalihu @borisyankov what do you think?

**Comment by borisyankov** [comment]
Merging. Plan for bigger refactoring soon :)

**Pull request merged**
