### PR TITLE
update unit test

### PR DESCRIPTION
**Pull request by bruce-binary**

### CODE REVIEW

**Comment by arnabk** [comment]
@nazaninreihani I this was related to your change. Please check if you could run tests before submitting PR.

**Comment by nazaninreihani** [comment]
@arnabk sorry for that, sure

**Comment by arnabk** [comment]
@nazaninreihani It is ok. Not a big deal. Sometimes I am lazy too to run some `yarn test:full` :)
The problem is, when I merge anybody's PR, I just move the card to `released to beta` without checking if the build failed or not (although I do get failed emails from travis). QA might reopen your card if they do not see your changes.

**Comment by nazaninreihani** [comment]
@arnabk you're right, I'll try not to forget to run tests :)

**Pull request merged**
