### PR TITLE
Qingwei/tester issue

### PR DESCRIPTION
**Pull request by qingweibinary**
I feel it's not reliable, as the same code was not working for half an hour, any idea ?

### CODE REVIEW

**Comment by borisyankov** [comment]
You don't seem to be handling the fact that the user can quit by clicking Esc or other ways?

**Comment by qingweibinary** [comment]
@borisyankov
Argh, will fix

**Comment by qingweibinary** [comment]
@borisyankov Added handling code ~

**Comment by borisyankov** [comment]
It is better as a separate component. I'll do it.

**Pull request merged**
