### PR TITLE
Add validation check for trading time.

### PR DESCRIPTION
**Pull request by bruce-binary**
I know that other components with validation code have an additional "*.validation.config.js", but just for one validation check I find it a hassle so it's all done in the same file. 

Also there is a lot of duplicate code in validation files. A lot of logic here can be shared - I could work on refactoring that as separate pull request.

### CODE REVIEW

**Comment by arnabk** [comment]
@brucebinary Why is it an overhead to just move the code that you have written in the same file, to a file called *.validation.config.js? I believe in JS we are used to writing single file per function too. My worry is, it starts with one method and then grows so fast that we put another refactoring effort to reduce the main file length.

**Comment by brucebinary** [comment]
I see your point. I'll work on refactoring the validation code to a separate file and update this request.

**Comment by brucebinary** [comment]
hm. This does meant errors is a nested object in state. But It's to keep consistent with other files.

I'm also wondering why use head() function? a[0] does the same thing. The library is only a few hundred bytes though.

**Comment by brucebinary** [comment]
Actually it might be better to use head(). Just to be consistent. Thoughts?

**Comment by arnabk** [comment]
@brucebinary You asked a genuine question and that has been discussed in lodash github project.
https://github.com/lodash/lodash/issues/2732

However in this case, its all about consistency.

**Pull request merged**
