### PR TITLE
Fix stake or amount in trades

### PR DESCRIPTION
**Pull request by DanSallau**
Hi,

Attached contained few changes that should address the following ticket for your perusal. https://trello.com/c/opiISpUY/533-make-default-params-of-each-trade-different

### CODE REVIEW

**Comment by borisyankov** [comment]
I don't think we want to do it this way.
Also, if the user changes the stake, he will still encounter the error.

**Comment by qingweibinary** [comment]
Anyway, we should solve it now so it does not block us, I prefer to use different symbol/type rather than different stake

**Comment by borisyankov** [comment]
Differing asset might make more sense, but also might not.
This should not be an error. Backend is wrong and can fix it very easily.
@qingweibinary Can you push around a bit, it is like a critical bug for us now.

**Comment by qingweibinary** [comment]
@borisyankov ok, I am not 100% convince on how it should works, how about I fire an email discussion ?

**Comment by nuruddeensalihu** [comment]
"if the user changes the stake, he will still encounter the error." I don't think user would like his second trade params to match the first param or would he ? If he shouldn't then the error message would serve it purpose , thought not sure if the error message match the error type. Moreover, I don't think different asset would make more sense here considering user need to key in an amount regardless. That should be more convenient since its a text control compare to the said asset which involved a long list on a dropdown.

**Comment by qingweibinary** [comment]
@nuruddeensalihu we would not know, as he could actually just sum up stake in 1 trade.
Different asset make more sense because simply changing stake is the least unlikely what the client want

If I want a stake 30 and a stake 40, I would use stake 70, not having both 30 and 40.

I suggest we change asset now so that it's not blocking us, then we will work on the frontend caching as discussed in email I sent

**Comment by borisyankov** [comment]
Nope. None of the options make sense.
A user often trades on a single asset at a time.
He also often trades in similar stakes, especially for ticks at minimal value of 0.35 so just giving him 10, 20, 30, 40 stake is not helping anything.

And of course the user can likely have the same trade, there is another variable that he can vary - time. He can buy the first now, and the second few moments later.

**Pull request closed without merging**
