### PR TITLE
fix trackjs

### PR DESCRIPTION
**Pull request by nazaninreihani**

### CODE REVIEW

**Comment by arnabk** [comment]
@nazaninreihani Please submit this to master

**Comment by arnabk** [comment]
@brucebinary Could you please review this change and make sure that it is going to be fine in our mobile packaging (using cordova)

**Comment by brucebinary** [comment]
Why is this PR closed? The changes look good to me.

**Comment by nazaninreihani** [comment]
@brucebinary I submitted another PR to master we wanted it to be on master so I closed it

**Pull request closed without merging**
