### PR TITLE
Endpoint

### PR DESCRIPTION
**Pull request by nazaninreihani**

### CODE REVIEW

**Comment by arnabk** [comment]
@nazaninreihani Trello card?

**Comment by nazaninreihani** [comment]
@arnabk Sorry, I added the trello card, this is about adding front-end server as default server and make next-gen work with binary endpoint chrome plugin which is going to be released

**Comment by arnabk** [comment]
Closing this since the change has been taken care in https://github.com/binary-com/binary-next-gen/pull/710

**Comment by arnabk** [comment]
@nazaninreihani I think now I probably understand what these changes are for. Is it for your preparation to integrate with Chrome Ext?

**Comment by nazaninreihani** [comment]
@arnabk yes it is

**Comment by arnabk** [comment]
@nazaninreihani I was thinking to reopen this PR, but it looks like you already sent me these changes in the other PR. So we are good, I believe?

**Comment by nazaninreihani** [comment]
@arnabk yes sure

**Pull request closed without merging**
