### PR TITLE
Add upgrade to mobile devices, some fixes

### PR DESCRIPTION
**Pull request by nazaninreihani**

### CODE REVIEW

**Comment by arnabk** [comment]
@nazaninreihani What is this PR for? I could not relate it to any trello tasks

**Comment by nazaninreihani** [comment]
@arnabk As I talked to Ashkan we are going to add upgrade account to mobile devices as well, before now the link to upgrade was not shown in mobile devices

**Comment by arnabk** [comment]
@nazaninreihani Is it ready for merging?

**Comment by nazaninreihani** [comment]
@arnabk yes

**Pull request merged**
